default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: postgres
  host: localhost
  port: 5432

development:
  <<: *default
  database: car_rent_development

test:
  <<: *default
  database: car_rent_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
  database: car_rent_production
  username: postgres
  password: <%= ENV["RENDER_DEPLOY_DATABASE_PASSWORD"] %>
